<template>
  <div class="exam-publish-container">
    <h2 class="title">发布考试</h2>

    <div class="publish-form">
      <!-- 考试名称 -->
      <div class="form-row">
        <div class="form-item">
          <label>考试名称</label>
          <el-input placeholder="请输入考试名称" v-model="examInfo.testName"></el-input>
        </div>

        <!-- 课程选择 -->
        <div class="form-item">
          <label>选择课程</label>
          <el-select
              v-model="examInfo.courseId"
              placeholder="请选择课程"
              :loading="coursesLoading"
              @change="handleCourseChange"
          >
            <el-option
                v-for="course in courses"
                :key="course.id"
                :label="course.name"
                :value="course.id"
            />
          </el-select>
        </div>

        <!-- 章节选择 -->
        <div class="form-item">
          <label>选择章节</label>
          <el-select v-model="examInfo.chapterId" placeholder="请选择章节">
            <el-option
                v-for="chapter in chapters"
                :key="chapter.id"
                :label="`第 ${chapter.id} 章`"
                :value="chapter.id"
            />
          </el-select>
        </div>
      </div>

      <!-- 考试时长和时间 -->
      <div class="form-row">
        <div class="form-item">
          <label>考试时长</label>
          <el-input-number
              v-model="examInfo.duration"
              :min="10"
              :max="180"
              placeholder="请输入时长"
          >
            <template #append>分钟</template>
          </el-input-number>
        </div>

        <div class="form-item">
          <label>考试时间</label>
          <el-date-picker
              v-model="examInfo.startTime"
              type="datetime"
              placeholder="选择考试时间"
              format="YYYY-MM-DD HH:mm"
              value-format="YYYY-MM-DDTHH:mm:ss"
          />
        </div>
        
        <div class="form-item">
          <label>成绩比例</label>
          <el-input-number
              v-model="examInfo.ratio"
              :min="1"
              :max="100"
              placeholder="请输入比例"
          >
            <template #append>%</template>
          </el-input-number>
        </div>
      </div>

      <!-- 是否开卷和操作按钮 -->
      <div class="form-row">
        <div class="form-item">
          <label>是否开卷</label>
          <el-select placeholder="请选择" v-model="examInfo.isOpenBook">
            <el-option label="开卷" :value="true"></el-option>
            <el-option label="闭卷" :value="false"></el-option>
          </el-select>
        </div>

        <div class="form-item">
          <label>试卷管理</label>
          <el-button type="primary" @click="showDialog = true">编辑试卷</el-button>
        </div>

        <div class="form-item">
          <label>自动生成</label>
          <el-button type="success" @click="showAutoGenerateDialog = true">自动生成试卷</el-button>
        </div>

<!--        <div class="form-item">-->
<!--          <label>查看试卷</label>-->
<!--          <el-button @click="viewPaper" :disabled="selectedQuestions.length === 0">查看</el-button>-->
<!--        </div>-->
      </div>

      <!-- 通知学生 -->
      <div class="form-row">
        <div class="form-item">
          <el-checkbox v-model="examInfo.notifyStudents">通知学生</el-checkbox>
        </div>
      </div>

      <!-- 试卷预览 -->
      <div v-if="selectedQuestions.length > 0" class="form-row">
        <div class="form-item" style="flex: 1;">
          <label>试卷预览：</label>
          <ul>
            <li v-for="(q, index) in selectedQuestions"
                :key="index"
                style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 5px;"
            >
              {{ index + 1 }}. {{ q.content }}
              <el-button
                  type="danger"
                  size="small"
                  icon="el-icon-delete"
                  @click="removeQuestion(q.question_id)"
              >删除</el-button>
            </li>
          </ul>
        </div>
      </div>

      <!-- 操作按钮 -->
      <div class="form-actions">
        <el-button type="primary" @click="createAndPublishExam" :loading="publishing">发布</el-button>
        <el-button @click="resetForm">重置</el-button>
      </div>
    </div>

    <!-- 编辑试卷对话框 -->
    <el-dialog title="编辑试卷" v-model="showDialog" width="800px">
      <div class="form-row">
        <el-input v-model="searchKeyword" placeholder="输入题号或题干关键字" style="margin-right: 10px; flex: 1" />
        <el-button @click="searchQuestions">搜索</el-button>
      </div>
      <el-table :data="searchResults" style="margin-top: 10px" height="300px">
        <el-table-column prop="question_id" label="题号" width="80" />
        <el-table-column prop="content" label="题干" />
        <el-table-column label="操作" width="120">
          <template #default="scope">
            <el-button size="small" type="success" @click="addQuestion(scope.row)">添加</el-button>
          </template>
        </el-table-column>
      </el-table>
      <template #footer>
        <el-button @click="showDialog = false">关闭</el-button>
      </template>
    </el-dialog>

    <!--自动生成对话框-->
    <el-dialog title="自动生成试卷" v-model="showAutoGenerateDialog" width="400px">
      <div class="form-row" style="flex-direction: column;">
        <div class="form-item">
          <label>选择题数量</label>
          <el-input-number v-model="choiceCount" :min="0" :max="50" />
        </div>
        <div class="form-item">
          <label>判断题数量</label>
          <el-input-number v-model="judgeCount" :min="0" :max="50" />
        </div>
      </div>
      <template #footer>
        <el-button @click="showAutoGenerateDialog = false">取消</el-button>
        <el-button type="primary" @click="handleAutoGenerateConfirm">确认生成</el-button>
      </template>
    </el-dialog>

  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import axios from 'axios'
import { ElMessage } from 'element-plus'
import { useuserLoginStore } from '../../../store/userLoginStore'

const userStore = useuserLoginStore()

// 创建api实例，与其他online_test模块使用相同的配置
const api = axios.create({
  baseURL: 'http://localhost:8080',
  headers: {
    'Content-Type': 'application/json',
  },
})

// 从用户状态获取教师ID
const teacherId = ref(Number(userStore.loginUser.user_id) || 29)

// 响应式数据
const examInfo = reactive({
  testName: '',
  courseId: '',
  chapterId: '',
  duration: 60,
  startTime: '',
  isOpenBook: false,
  notifyStudents: true,
  isRandom: 0,
  ratio: 100 // 默认为100%
})

const courses = ref([])
const chapters = ref([])
const selectedChapter = ref([])
const selectedQuestions = ref([])
const coursesLoading = ref(false)
const publishing = ref(false)
const showDialog = ref(false)
const searchKeyword = ref('')
const searchResults = ref([])
const showAutoGenerateDialog = ref(false)
const choiceCount = ref(5)
const judgeCount = ref(5)

onMounted(() => {
  fetchCourses()
})

async function fetchCourses() {
  coursesLoading.value = true
  try {
    const response = await api.get(`test/questions/course/${teacherId.value}`)
    courses.value = response.data.map(course => ({ id: course.course_id, name: course.course_name }))
  } catch (error) {
    ElMessage.error("加载课程列表失败")
  } finally {
    coursesLoading.value = false
  }
}

async function handleCourseChange(courseId) {
  if (!courseId) return
  selectedQuestions.value = []
  examInfo.chapterId = ''
  try {
    const res = await api.get(`/test/questions/getQuestionByCourse`, {
      params: {
        courseId: courseId
      }
    })
    const allQuestions = res.data || []
    // 提取章节信息（去重）
    const chapterMap = new Map()
    allQuestions.forEach(q => {
      if (q.chapter_id && !chapterMap.has(q.chapter_id)) {
        chapterMap.set(q.chapter_id)
      }
    })
    chapters.value = Array.from(chapterMap, ([id]) => ({ id }))

  } catch (err) {
    ElMessage.error('加载章节失败')
  }
}

async function searchQuestions() {
  if (!examInfo.courseId || !examInfo.chapterId) {
    ElMessage.warning('请先选择课程和章节')
    return
  }
  try {
    const res = await api.get(`/test/questions/getQuestionByCourse`, {
      params: {
        courseId: examInfo.courseId,
        chapter_id: examInfo.chapterId
      }
    })
    const allQuestions = res.data || []
    const keyword = searchKeyword.value.trim().toLowerCase()
    searchResults.value = allQuestions.filter(q =>
        q.question_id.toString().includes(keyword) ||
        q.content.toLowerCase().includes(keyword)
    )
  } catch (error) {
    ElMessage.error('查询题目失败')
  }
}

function addQuestion(question) {
  if (!selectedQuestions.value.find(q => q.question_id === question.question_id)) {
    selectedQuestions.value.push(question)
  }
}

function removeQuestion(questionId) {
  selectedQuestions.value = selectedQuestions.value.filter(q => q.question_id !== questionId)
}

async function handleAutoGenerateConfirm() {
  if (!examInfo.courseId || !examInfo.chapterId) {
    ElMessage.warning('请先选择课程和章节')
    return
  }

  try {
    const res = await api.get(`/test/questions/getQuestionByCourse`, {
      params: {
        courseId: examInfo.courseId,
        chapter_id: examInfo.chapterId
      }
    })
    const allQuestions = res.data || []

    const choiceQuestions = allQuestions.filter(q => q.question_type === 'MC')
    const judgeQuestions = allQuestions.filter(q => q.question_type === 'TF')

    const shuffle = arr => arr.sort(() => 0.5 - Math.random())
    const selectedChoices = shuffle(choiceQuestions).slice(0, choiceCount.value)
    const selectedJudges = shuffle(judgeQuestions).slice(0, judgeCount.value)

    selectedQuestions.value = [...selectedChoices, ...selectedJudges]
    showAutoGenerateDialog.value = false

    examInfo.isRandom = 1
    ElMessage.success(`生成成功：选择题${selectedChoices.length}题，判断题${selectedJudges.length}题`)
  } catch (error) {
    ElMessage.error('生成失败，请稍后重试')
  }
}

async function createAndPublishExam() {
  if (!validateForm()) return
  publishing.value = true
  
  const deadline = new Date(
    new Date(examInfo.startTime.replace(' ', 'T')).getTime() + 
    examInfo.duration * 60000
  )

  const startDate = new Date(examInfo.startTime)

  const formatLocalTime = (date) => {
    // 获取本地时间与UTC的偏移量（分钟）
    //const offset = date.getTimezoneOffset(); // 中国时区返回-480
    
    // 计算需要调整的毫秒数（中国时区UTC+8需要加上8小时）
    const adjustMs = (8 * 60) * 60 * 1000;//(16 * 60 + offset) * 60 * 1000;
    
    const adjustedDate = new Date(date.getTime() + adjustMs)
    
    const pad = (num) => num.toString().padStart(2, '0')
    return `${adjustedDate.getFullYear()}-${pad(adjustedDate.getMonth() + 1)}-${pad(adjustedDate.getDate())}T${pad(adjustedDate.getHours())}:${pad(adjustedDate.getMinutes())}`
  }

  try {
    // 转换数据格式以匹配后端要求
    const requestData = {
      testName: examInfo.testName,
      teacherId: teacherId.value,
      courseId: examInfo.courseId,
      publishTime: formatLocalTime(startDate),
      deadline: formatLocalTime(deadline),
      questionCount: selectedQuestions.value.length,
      isRandom: examInfo.isRandom,
      questionIds: selectedQuestions.value.map(q => q.question_id),
      ratio: examInfo.ratio,
      // 添加一个参数表示直接发布，不需要再调用publish
      isPublished: true
    }

    console.log("发送给后端的数据:", requestData)
    
    // 合并为一个API调用，只使用generate接口
    const createRes = await api.post('/test/testPublish/generate', requestData)
    const testId = createRes.data
    console.log("考试创建成功，testId:", testId)
    
    // 移除第二个publish API调用
    // ================删除下面这段代码================
    // const params = new URLSearchParams()
    // params.append('testId', testId)
    // params.append('publishTime', formatLocalTime(startDate))
    // await api.post('/test/testPublish/publish', params, {
    //   headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
    // })
    
    ElMessage.success('考试发布成功！')
    resetForm()
  } catch (err) {
    console.error('发布考试错误:', err)
    ElMessage.error(`考试发布失败: ${err.response?.data?.message || err.message}`)
  } finally {
    publishing.value = false
  }
}

// 新增辅助方法：格式化日期时间
function formatDateTime(dateTimeStr) {
  // 将 "2025-05-30 14:39" 转为 "2025-05-30T14:39:00"
  return dateTimeStr.replace(' ', 'T') + ':00'
}

function calculateDeadline() {
  // 1. 转换为 Date 对象
  const startDate = new Date(examInfo.startTime)
  
  // 2. 计算结束时间
  const endDate = new Date(startDate.getTime() + examInfo.duration * 60000)
  
  // 3. 格式化为 ISO 8601（带 T 分隔符）
  const pad = num => num.toString().padStart(2, '0')
  const isoString = `${endDate.getFullYear()}-${pad(endDate.getMonth() + 1)}-${pad(endDate.getDate())}T${pad(endDate.getHours())}:${pad(endDate.getMinutes())}:00`
  
  return isoString
}

function validateForm() {
  if (!examInfo.testName) {
    ElMessage.warning('请输入考试名称')
    return false
  }
  if (!examInfo.courseId || !examInfo.chapterId) {
    ElMessage.warning('请选择课程和章节')
    return false
  }
  if (!examInfo.startTime) {
    ElMessage.warning('请选择考试时间')
    return false
  }
  if (selectedQuestions.value.length === 0) {
    ElMessage.warning('请选择题目')
    return false
  }
  if (!examInfo.duration) {
    ElMessage.warning('请输入考试时长')
    return false
  }
  if (!examInfo.ratio || examInfo.ratio < 1 || examInfo.ratio > 100) {
    ElMessage.warning('请输入1-100之间的成绩比例')
    return false
  }
  return true
}

function resetForm() {
  Object.assign(examInfo, {
    testName: '',
    courseId: '',
    chapterId: '',
    duration: 60,
    startTime: '',
    isOpenBook: false,
    notifyStudents: true,
    isRandom: 0,
    ratio: 100 // 重置为100%
  })
  selectedQuestions.value = []
  searchResults.value = []
  searchKeyword.value = ''
}
</script>

<style scoped>
.exam-publish-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: 'Microsoft YaHei', sans-serif;
}

.title {
  text-align: center;
  margin-bottom: 30px;
  color: #333;
}

.publish-form {
  background: #fff;
  padding: 20px;
  border-radius: 4px;
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);
}

.form-row {
  display: flex;
  margin-bottom: 20px;
  flex-wrap: wrap;
}

.form-item {
  flex: 1;
  margin-right: 20px;
}

.form-item:last-child {
  margin-right: 0;
}

.form-item label {
  display: block;
  margin-bottom: 8px;
  font-size: 14px;
  color: #606266;
}

.form-actions {
  text-align: center;
  margin-top: 30px;
}
</style>
