<template>
  <div class="exam-publish-container">
    <h2 class="title">发布考试</h2>

    <div class="publish-form">
      <!-- 考试名称 -->
      <div class="form-row">
        <div class="form-item">
          <label>考试名称</label>
          <el-input placeholder="请输入考试名称" v-model="examInfo.testName"></el-input>
        </div>

        <!-- 课程选择 -->
        <div class="form-item">
          <label>选择课程</label>
          <el-select
              v-model="examInfo.courseId"
              placeholder="请选择课程"
              :loading="coursesLoading"
              @change="handleCourseChange"
          >
            <el-option
                v-for="course in courses"
                :key="course.id"
                :label="course.name"
                :value="course.id"
            />
          </el-select>
        </div>

        <!-- 章节选择 -->
        <div class="form-item">
          <label>选择章节</label>
          <el-select v-model="examInfo.chapterId" placeholder="请选择章节">
            <el-option
                v-for="chapter in chapters"
                :key="chapter.id"
                :label="`第 ${chapter.id} 章`"
                :value="chapter.id"
            />
          </el-select>
        </div>
      </div>

      <!-- 考试时长和时间 -->
      <div class="form-row">
        <div class="form-item">
          <label>考试时长</label>
          <el-input-number
              v-model="examInfo.duration"
              :min="10"
              :max="180"
              placeholder="请输入时长"
          >
            <template #append>分钟</template>
          </el-input-number>
        </div>

        <div class="form-item">
          <label>考试时间</label>
          <el-date-picker
              v-model="examInfo.startTime"
              type="datetime"
              placeholder="选择考试时间"
              format="YYYY-MM-DD HH:mm"
              value-format="YYYY-MM-DDTHH:mm:ss"
          />
        </div>
      </div>

      <!-- 是否开卷和操作按钮 -->
      <div class="form-row">
        <div class="form-item">
          <label>是否开卷</label>
          <el-select placeholder="请选择" v-model="examInfo.isOpenBook">
            <el-option label="开卷" :value="true"></el-option>
            <el-option label="闭卷" :value="false"></el-option>
          </el-select>
        </div>

        <div class="form-item">
          <label>试卷管理</label>
          <el-button type="primary" @click="showDialog = true">编辑试卷</el-button>
        </div>

        <div class="form-item">
          <label>自动生成</label>
          <el-button type="success" @click="showAutoGenerateDialog = true">自动生成试卷</el-button>
        </div>

<!--        <div class="form-item">-->
<!--          <label>查看试卷</label>-->
<!--          <el-button @click="viewPaper" :disabled="selectedQuestions.length === 0">查看</el-button>-->
<!--        </div>-->
      </div>

      <!-- 通知学生 -->
      <div class="form-row">
        <div class="form-item">
          <el-checkbox v-model="examInfo.notifyStudents">通知学生</el-checkbox>
        </div>
      </div>

      <!-- 试卷预览 -->
      <div v-if="selectedQuestions.length > 0" class="form-row">
        <div class="form-item" style="flex: 1;">
          <label>试卷预览：</label>
          <ul>
            <li v-for="(q, index) in selectedQuestions"
                :key="index"
                style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 5px;"
            >
              {{ index + 1 }}. {{ q.content }}
              <el-button
                  type="danger"
                  size="small"
                  icon="el-icon-delete"
                  @click="removeQuestion(q.question_id)"
              >删除</el-button>
            </li>
          </ul>
        </div>
      </div>

      <!-- 操作按钮 -->
      <div class="form-actions">
        <el-button type="primary" @click="createAndPublishExam" :loading="publishing">发布</el-button>
        <el-button @click="resetForm">重置</el-button>
      </div>
    </div>

    <!-- 编辑试卷对话框 -->
    <el-dialog title="编辑试卷" v-model="showDialog" width="800px">
      <div class="form-row">
        <el-input v-model="searchKeyword" placeholder="输入题号或题干关键字" style="margin-right: 10px; flex: 1" />
        <el-button @click="searchQuestions">搜索</el-button>
      </div>
      <el-table :data="searchResults" style="margin-top: 10px" height="300px">
        <el-table-column prop="question_id" label="题号" width="80" />
        <el-table-column prop="content" label="题干" />
        <el-table-column label="操作" width="120">
          <template #default="scope">
            <el-button size="small" type="success" @click="addQuestion(scope.row)">添加</el-button>
          </template>
        </el-table-column>
      </el-table>
      <template #footer>
        <el-button @click="showDialog = false">关闭</el-button>
      </template>
    </el-dialog>

    <!--自动生成对话框-->
    <el-dialog title="自动生成试卷" v-model="showAutoGenerateDialog" width="400px">
      <div class="form-row" style="flex-direction: column;">
        <div class="form-item">
          <label>选择题数量</label>
          <el-input-number v-model="choiceCount" :min="0" :max="50" />
        </div>
        <div class="form-item">
          <label>判断题数量</label>
          <el-input-number v-model="judgeCount" :min="0" :max="50" />
        </div>
      </div>
      <template #footer>
        <el-button @click="showAutoGenerateDialog = false">取消</el-button>
        <el-button type="primary" @click="handleAutoGenerateConfirm">确认生成</el-button>
      </template>
    </el-dialog>

  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'LaunchTest',
  data() {
    return {
      examInfo: {
        testName: '',
        courseId: '',
        chapterId: '',
        duration: 60,
        startTime: '',
        isOpenBook: false,
        notifyStudents: true,
        isRandom: 0
      },
      courses: [],
      chapters: [],
      selectedChapter: [],
      selectedQuestions: [],
      coursesLoading: false,
      publishing: false,
      showDialog: false,
      searchKeyword: '',
      searchResults: [],
      showAutoGenerateDialog: false,
      choiceCount: 5,
      judgeCount: 5,
      teacherId: 29, // 假设当前教师ID，实际应从登录信息获取
      
    }
  },
  created() {
    this.fetchCourses();
  },
  methods: {
    async fetchCourses() {
      this.coursesLoading = true;
      try {
        const response = await axios.get(`test/questions/course/${this.teacherId}`);
        this.courses = response.data.map(course => ({ id: course.course_id, name: course.course_name }));
      } catch (error) {
        this.$message.error("加载课程列表失败");
      } finally {
        this.coursesLoading = false;
      }
    },

    async handleCourseChange(courseId) {
      if (!courseId) return;
      this.selectedQuestions = [];
      this.examInfo.chapterId = '';
      try {
        const res = await axios.get(`/test/questions/getQuestionByCourse`, {
          params: {
            courseId: courseId
          }
        });
        const allQuestions = res.data || [];
        // 提取章节信息（去重）
        const chapterMap = new Map();
        allQuestions.forEach(q => {
          if (q.chapter_id && !chapterMap.has(q.chapter_id)) {
            chapterMap.set(q.chapter_id);
          }
        });
        this.chapters = Array.from(chapterMap, ([id]) => ({ id }));

      } catch (err) {
        this.$message.error('加载章节失败');
      }
    },

    async searchQuestions() {
      if (!this.examInfo.courseId || !this.examInfo.chapterId) {
        this.$message.warning('请先选择课程和章节');
        return;
      }
      try {
        const res = await axios.get(`/test/questions/getQuestionByCourse`, {
          params: {
            courseId: this.examInfo.courseId,
            chapter_id: this.examInfo.chapterId
          }
        });
        const allQuestions = res.data || [];
        const keyword = this.searchKeyword.trim().toLowerCase();
        this.searchResults = allQuestions.filter(q =>
            q.question_id.toString().includes(keyword) ||
            q.content.toLowerCase().includes(keyword)
        );
      } catch (error) {
        this.$message.error('查询题目失败');
      }
    },

    addQuestion(question) {
      if (!this.selectedQuestions.find(q => q.question_id === question.question_id)) {
        this.selectedQuestions.push(question);
      }
    },

    removeQuestion(questionId) {
      this.selectedQuestions = this.selectedQuestions.filter(q => q.question_id !== questionId);
    },

    async handleAutoGenerateConfirm() {
      if (!this.examInfo.courseId || !this.examInfo.chapterId) {
        this.$message.warning('请先选择课程和章节');
        return;
      }

      try {
        const res = await axios.get(`/test/questions/getQuestionByCourse`, {
          params: {
            courseId: this.examInfo.courseId,
            chapter_id: this.examInfo.chapterId
          }
        });
        const allQuestions = res.data || [];

        const choiceQuestions = allQuestions.filter(q => q.question_type === 'MC');
        const judgeQuestions = allQuestions.filter(q => q.question_type === 'TF');

        const shuffle = arr => arr.sort(() => 0.5 - Math.random());
        const selectedChoices = shuffle(choiceQuestions).slice(0, this.choiceCount);
        const selectedJudges = shuffle(judgeQuestions).slice(0, this.judgeCount);

        this.selectedQuestions = [...selectedChoices, ...selectedJudges];
        this.showAutoGenerateDialog = false;

        this.examInfo.isRandom = 1;
        this.$message.success(`生成成功：选择题${selectedChoices.length}题，判断题${selectedJudges.length}题`);
      } catch (error) {
        this.$message.error('生成失败，请稍后重试');
      }
    },

    async createAndPublishExam() {
      if (!this.validateForm()) return;
      this.publishing = true;
      
      const deadline = new Date(
        new Date(this.examInfo.startTime.replace(' ', 'T')).getTime() + 
        this.examInfo.duration * 60000
      );

      const startDate = new Date(this.examInfo.startTime);

      const formatLocalTime = (date) => {
        // 获取本地时间与UTC的偏移量（分钟）
        //const offset = date.getTimezoneOffset(); // 中国时区返回-480
        
        // 计算需要调整的毫秒数（中国时区UTC+8需要加上8小时）
        const adjustMs = (8 * 60) * 60 * 1000;//(16 * 60 + offset) * 60 * 1000;
        
        const adjustedDate = new Date(date.getTime() + adjustMs);
        
        const pad = (num) => num.toString().padStart(2, '0');
        return `${adjustedDate.getFullYear()}-${pad(adjustedDate.getMonth() + 1)}-${pad(adjustedDate.getDate())}T${pad(adjustedDate.getHours())}:${pad(adjustedDate.getMinutes())}`;
      };

      try {
        // 转换数据格式以匹配后端要求
        const requestData = {
          testName: this.examInfo.testName, // 注意字段名转换
          teacherId: this.teacherId, // 从组件数据中获取或使用固定值
          courseId: this.examInfo.courseId,
          publishTime: formatLocalTime(startDate),
          deadline: formatLocalTime(deadline), // 根据duration计算截止时间
          questionCount: this.selectedQuestions.length,
          isRandom: this.examInfo.isRandom, // 假设0表示非随机
          questionIds: this.selectedQuestions.map(q => q.question_id) // 直接发送数组 JSON.stringify(this.selectedQuestions.map(q => q.question_id)) // 转为JSON字符串
        };

        console.log("发送给后端的数据:", requestData);
        console.log("实际发送的teacher_id:", this.teacherId, "类型:", typeof this.teacherId);
        console.log("完整请求数据:", JSON.stringify(requestData, null, 2));
        console.log("请求headers:", axios.defaults.headers);

        const createRes = await axios.post('/test/testPublish/generate', requestData);
        //console.log("完整数据:", createRes.data);
        const testId = createRes.data;
        console.log("testId 类型:", typeof testId); // 输出类型（number/object）
        console.log("testId 内容:", testId); // 输出具体内容
        const params = new URLSearchParams();
        params.append('testId', testId);
        params.append('publishTime', formatLocalTime(startDate));
        await axios.post('/test/testPublish/publish', params, {
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
        });
        //await axios.post('/test/testPublish/publish', { testId: testId });
        
        this.$message.success('考试发布成功！');
        this.resetForm();
      } catch (err) {
        console.error('发布考试错误:', err);
        this.$message.error(`考试发布失败: ${err.response?.data?.message || err.message}`);
      } finally {
        this.publishing = false;
      }
    },

    // 新增辅助方法：格式化日期时间
    formatDateTime(dateTimeStr) {
      // 将 "2025-05-30 14:39" 转为 "2025-05-30T14:39:00"
      return dateTimeStr.replace(' ', 'T') + ':00';
    },

    calculateDeadline() {
      // 1. 转换为 Date 对象
      const startDate = new Date(this.examInfo.startTime);
      
      // 2. 计算结束时间
      const endDate = new Date(startDate.getTime() + this.examInfo.duration * 60000);
      
      // 3. 格式化为 ISO 8601（带 T 分隔符）
      const pad = num => num.toString().padStart(2, '0');
      const isoString = `${endDate.getFullYear()}-${pad(endDate.getMonth() + 1)}-${pad(endDate.getDate())}T${pad(endDate.getHours())}:${pad(endDate.getMinutes())}:00`;
      
      return isoString;
    },

    validateForm() {
      if (!this.examInfo.testName) {
        this.$message.warning('请输入考试名称');
        return false;
      }
      if (!this.examInfo.courseId || !this.examInfo.chapterId) {
        this.$message.warning('请选择课程和章节');
        return false;
      }
      if (!this.examInfo.startTime) {
        this.$message.warning('请选择考试时间');
        return false;
      }
      if (this.selectedQuestions.length === 0) {
        this.$message.warning('请选择题目');
        return false;
      }
      if (!this.examInfo.duration) {
        this.$message.warning('请输入考试时长');
        return false;
      }
      return true;
    },

    resetForm() {
      this.examInfo = {
        testName: '',
        courseId: '',
        chapterId: '',
        duration: 60,
        startTime: '',
        isOpenBook: false,
        notifyStudents: true
      };
      this.selectedQuestions = [];
      this.searchResults = [];
      this.searchKeyword = '';
    }
  }
}
</script>

<style scoped>
.exam-publish-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: 'Microsoft YaHei', sans-serif;
}

.title {
  text-align: center;
  margin-bottom: 30px;
  color: #333;
}

.publish-form {
  background: #fff;
  padding: 20px;
  border-radius: 4px;
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.1);
}

.form-row {
  display: flex;
  margin-bottom: 20px;
  flex-wrap: wrap;
}

.form-item {
  flex: 1;
  margin-right: 20px;
}

.form-item:last-child {
  margin-right: 0;
}

.form-item label {
  display: block;
  margin-bottom: 8px;
  font-size: 14px;
  color: #606266;
}

.form-actions {
  text-align: center;
  margin-top: 30px;
}
</style>
